version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=min-helper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build:
      dockerfile: backend/Dockerfile
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  vue:
    build:
      dockerfile: frontend/Dockerfile
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - web
