version: '3'

services:
  web:
    build: .
    container_name: min-helper_web
    command: "gunicorn --chdir backend --workers=2 --bind=0.0.0.0 config.wsgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "postgres:latest"
    container_name: min-helper_db
    environment:
      - POSTGRES_DB=min-helper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  vue:
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - web
