# Generated by Django 4.0.1 on 2022-01-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('english_name', models.CharField(blank=True, max_length=175, null=True)),
                ('japanese_name', models.CharField(blank=True, max_length=175, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.CharField(blank=True, max_length=25, null=True)),
                ('end_date', models.CharField(blank=True, max_length=25, null=True)),
                ('episodes_count', models.SmallIntegerField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='animes.Category')),
            ],
        ),
    ]
