# Generated by Django 4.0.1 on 2022-01-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='anime',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
