# Generated by Django 4.0.1 on 2022-01-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_alter_category_options_anime_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='episode_duration',
        ),
    ]
