# Generated by Django 4.0.1 on 2022-01-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_remove_anime_episode_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='banner_image',
        ),
    ]
