# Generated by Django 4.0.1 on 2022-01-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_remove_anime_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='end_date',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='anime',
            name='start_date',
            field=models.CharField(max_length=25),
        ),
    ]
