# Generated by Django 4.0.1 on 2022-01-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0005_alter_anime_end_date_alter_anime_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episodes_count',
            field=models.CharField(max_length=4),
        ),
    ]
