# Generated by Django 4.0.1 on 2022-01-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0008_alter_anime_episodes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episodes_count',
            field=models.CharField(max_length=50),
        ),
    ]
