# Generated by Django 4.0.1 on 2022-01-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0012_alter_anime_end_date_alter_anime_episodes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='english_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes_count',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
