# Generated by Django 4.0.1 on 2022-01-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0013_alter_anime_english_name_alter_anime_episodes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episodes_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
