# Generated by Django 4.0.1 on 2022-01-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0014_alter_anime_episodes_count_alter_anime_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='japanese_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
