# Generated by Django 4.0.1 on 2022-01-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0015_alter_anime_english_name_alter_anime_japanese_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='english_name',
            field=models.CharField(blank=True, max_length=175, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='japanese_name',
            field=models.CharField(blank=True, max_length=175, null=True),
        ),
    ]
