# Generated by Django 4.0.1 on 2022-01-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0016_alter_anime_english_name_alter_anime_japanese_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='category',
            new_name='categories',
        ),
    ]
